version: '3'
services:
  config-service:
    image: justamitsaha/config-service
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - high-tech-bank
    environment:
      git.cred: "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"

  discovery-service:
    image: justamitsaha/discovery-service
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - high-tech-bank
    depends_on:
      - config-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      spring_profiles_active: localDocker
      spring_config_import: config-service:http://config-service:9000/configService
  api-gate-way-service:
    image: justamitsaha/api-gate-way-service
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - high-tech-bank
    depends_on:
      - config-service
      - discovery-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      spring_profiles_active: localDocker
      spring_config_import: config-service:http://config-service:9000/configService
networks:
  high-tech-bank: